version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bankcards_postgres
    environment:
      POSTGRES_DB: bankcards_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bankcards-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bankcards_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bankcards_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: mySecretKeyForJWTTokenGenerationMustBeLongEnough12345
      ENCRYPTION_SECRET: myEncryptionSecretKey32Bytes!
    ports:
      - "8080:8080"
    networks:
      - bankcards-network

volumes:
  postgres_data:

networks:
  bankcards-network:
    driver: bridge
