spring:
  application:
    name: bank-cards-management

  datasource:
    url: jdbc:postgresql://localhost:5432/bankcards_db
    username: postgres
    password: rootroot
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
    enabled: true
    default-schema: public

server:
  port: 8080

jwt:
  secret: mySecretKeyForJWTTokenGenerationMustBeLongEnough12345
  expiration: 86400000

encryption:
  secret-key: myEncryptionSecretKey32Bytes!
  algorithm: AES

logging:
  level:
    com.example.bankcards: DEBUG
    org.springframework.boot: INFO
    org.springframework.boot.autoconfigure: DEBUG
    org.hibernate: INFO
    org.liquibase: DEBUG
